name: Test & Coverage


on:
  workflow_call:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - run: ./mvnw --batch-mode --update-snapshots test

  verify:
    name: Integration Test
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - run: ./mvnw --batch-mode --update-snapshots verify

  coverage:
    name: Coverage Report
    needs: [test, verify]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: maven
      - name: Run coverage
        run: ./mvnw -B verify -Pcoverage --no-transfer-progress
