name: Feature Branch


on:
  workflow_call:
    inputs:
      environment:
        description: 'Job to run.'
        type: string
        required: false
        default: 'dev'
      pom-path:
        description: 'Pom path.'
        type: string
        required: false
        default: '../..'
#  workflow_dispatch:

#      version:
#        required: true
#        type: string
#    secrets:
#      MAVEN_USERNAME:
#        required: true
#      MAVEN_PASSWORD:
#        required: true
#      MAVEN_GPG_PASSPHRASE:
#        required: true

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: ./mvnw --batch-mode --update-snapshots test

  verify:
    name: Integration Test
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: ./mvnw --batch-mode --update-snapshots verify

  coverage:
    name: Coverage Report
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Run coverage
        run: ./mvnw -B verify -Pcoverage --no-transfer-progress
#      - name: codecov jacoco report
#        uses: codecov/codecov-action@v1
#          with:
#            file: ./**/target/site/jacoco/jacoco.xml
#            name: codecov
##
  upload-artifact-to-github:
    name: Upload Artifact To Github
    needs: [verify,coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: ./mvnw install -Dmaven.test.skip=true --batch-mode --update-snapshots
      - name: Upload Jar to stagging
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
