name: Feature Branch


on:
  workflow_call:
    inputs:
      environment:
        description: 'Job to run.'
        type: string
        required: false
        default: 'dev'
      pom-path:
        description: 'Pom path.'
        type: string
        required: false
        default: '../..'

jobs:
  call-workflow:
    uses: ./github-ci-maven.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}

  upload-artifact-to-github:
    name: Upload Artifact To Github
    needs: [ verify,coverage ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: ./mvnw install -Dmaven.test.skip=true --batch-mode --update-snapshots
      - name: Upload Jar to stagging
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
