name: Publish Artifact

on:
  workflow_call:
    inputs:
      environment:
        description: 'Job to run.'
        type: string
        required: false
        default: 'prod'

jobs:

  publish:
    name: Publish to artifactory
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_OSSRH_TOKEN # env variable for token in deploy
          gpg-private-key: MAVEN_GPG_SECRET_KEY # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Publish to Maven Central
        run: ./mvnw clean deploy -B -Prelease --batch-mode -D skipTests --no-transfer-progress
      # - name: Clean up
      #   run: rm "${HOME}/.m2/settings.xml"