name: Feature Branch


on:
  workflow_call:
#    inputs:
#      name:
#        required: true
#        type: string
#      version:
#        required: true
#        type: string
#    secrets:
#      MAVEN_USERNAME:
#        required: true
#      MAVEN_PASSWORD:
#        required: true
#      MAVEN_GPG_PASSPHRASE:
#        required: true

#on:
#  push:
#    branches-ignore:
#      - 'main'
#      - 'release*'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: ./mvnw -B install --no-transfer-progress

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - run: ./mvnw -B verify -P coverage --no-transfer-progress

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
