name: Feature Branch


on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
#      version:
#        required: true
#        type: string
#    secrets:
#      MAVEN_USERNAME:
#        required: true
#      MAVEN_PASSWORD:
#        required: true
#      MAVEN_GPG_PASSPHRASE:
#        required: true

#on:
#  push:
#    branches-ignore:
#      - 'main'
#      - 'release*'
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: ./mvnw --batch-mode --update-snapshots test

  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: ./mvnw --batch-mode --update-snapshots verify

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Run coverage
        run: ./mvnw clean  innstall -P coverage
#      -name: codecov jacoco report
#        uses: codecov/codecov-action@v1
#          with:
#            file: ./**/target/site/jacoco/jacoco.xml
#            name: codecov
##
#  upload:
#      needs: coverage
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v2
#        - name: Set up JDK 11
#          uses: actions/setup-java@v2
#          with:
#            java-version: '11'
#            distribution: 'adopt'
#            cache: maven
##        - name: Build with Maven
##          run: ./mvnw -P coverage --batch-mode --update-snapshots verify
#        - name: Upload Jar to stagging
#          run: mkdir staging && cp target/*.jar staging
#        -name: codecov jacoco report
#          uses: codecov/codecov-action@v1
#            with:
#              file: ./**/target/site/jacoco/jacoco.xml
#              name: codecov
#        - uses: actions/upload-artifact@v2
#         with:
#           name: Package
#           path: staging
